//
// AmenityCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Category classification for amenities */
public enum AmenityCategory: String, Sendable, Codable, CaseIterable {
    case foodBeverage = "food_beverage"
    case retail = "retail"
    case recreation = "recreation"
    case facility = "facility"
}
