//
// AmenityCalendarEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Amenity entry within a CalendarDay, showing per-amenity hours for a specific date. */
public struct AmenityCalendarEntry: Sendable, Codable, Hashable {

    /** Amenity UUID. */
    public var uuid: String
    /** Amenity name. */
    public var name: String
    /** Amenity category. */
    public var category: AmenityCategory
    /** Opening time in 24-hour format (HH:MM), in resort's local timezone.  `null` if this amenity is closed on this day. */
    public var opensAt: String?
    /** Closing time in 24-hour format (HH:MM), in resort's local timezone.  `null` if this amenity is closed on this day. */
    public var closesAt: String?

    public init(uuid: String, name: String, category: AmenityCategory, opensAt: String? = nil, closesAt: String? = nil) {
        self.uuid = uuid
        self.name = name
        self.category = category
        self.opensAt = opensAt
        self.closesAt = closesAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case name
        case category
        case opensAt = "opens_at"
        case closesAt = "closes_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(name, forKey: .name)
        try container.encode(category, forKey: .category)
        try container.encodeIfPresent(opensAt, forKey: .opensAt)
        try container.encodeIfPresent(closesAt, forKey: .closesAt)
    }
}

