//
// AmenitySchedule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Amenity schedule for the OperatingHours response */
public struct AmenitySchedule: Sendable, Codable, Hashable {

    /** Amenity UUID */
    public var uuid: String
    /** Amenity name */
    public var name: String
    /** Amenity category */
    public var category: AmenityCategory
    /** Operating schedules for this amenity */
    public var schedules: [Schedule]

    public init(uuid: String, name: String, category: AmenityCategory, schedules: [Schedule]) {
        self.uuid = uuid
        self.name = name
        self.category = category
        self.schedules = schedules
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case name
        case category
        case schedules
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(name, forKey: .name)
        try container.encode(category, forKey: .category)
        try container.encode(schedules, forKey: .schedules)
    }
}

