//
// Amenity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Minimal amenity info for trail map markers. */
public struct Amenity: Sendable, Codable, Hashable {

    public var description: String
    public var uuid: String
    public var name: String
    public var category: AmenityCategory
    public var website: String
    /** Today's scheduled opening time in 24-hour format (HH:MM), in resort's local timezone. */
    public var opensAt: String?
    /** Today's scheduled closing time in 24-hour format (HH:MM), in resort's local timezone. */
    public var closesAt: String?

    public init(description: String, uuid: String, name: String, category: AmenityCategory, website: String, opensAt: String? = nil, closesAt: String? = nil) {
        self.description = description
        self.uuid = uuid
        self.name = name
        self.category = category
        self.website = website
        self.opensAt = opensAt
        self.closesAt = closesAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case uuid
        case name
        case category
        case website
        case opensAt = "opens_at"
        case closesAt = "closes_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(description, forKey: .description)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(name, forKey: .name)
        try container.encode(category, forKey: .category)
        try container.encode(website, forKey: .website)
        try container.encodeIfPresent(opensAt, forKey: .opensAt)
        try container.encodeIfPresent(closesAt, forKey: .closesAt)
    }
}


extension Amenity: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if category == .unknownDefaultOpenApi { return true }
        return false
    }
}
