//
// AppConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** App-level configuration bundled into the aggregated report. */
public struct AppConfig: Sendable, Codable, Hashable {

    /** The resort's hosted base URL — scheme + host with no path, e.g.  `https://powder-mountain.mtnmanager.net`, or the resort's own custom  domain when one is configured. */
    public var hostedBaseUrl: String
    /** Last time the static trail-map assets were re-published, ISO 8601 UTC.  Bumped when those assets change so clients can cache-bust. */
    public var trailMapAssetsUpdatedAt: String

    public init(hostedBaseUrl: String, trailMapAssetsUpdatedAt: String) {
        self.hostedBaseUrl = hostedBaseUrl
        self.trailMapAssetsUpdatedAt = trailMapAssetsUpdatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hostedBaseUrl = "hosted_base_url"
        case trailMapAssetsUpdatedAt = "trail_map_assets_updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(hostedBaseUrl, forKey: .hostedBaseUrl)
        try container.encode(trailMapAssetsUpdatedAt, forKey: .trailMapAssetsUpdatedAt)
    }
}

