//
// AppReport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The aggregated report built for the mobile apps: every domain of the full  report inlined directly, plus the amenities list, trail-map summaries, and  mobile-app banners — all from a single request. Requires the &#x60;MobileApp&#x60;  entitlement; feature-gated sections (trail maps) come back empty rather than  erroring. */
public struct AppReport: Sendable, Codable, Hashable {

    public var resort: ResortInfo
    public var status: Overview
    /** Provides current snow conditions including base depth, surface conditions,  and snowfall totals in both metric and imperial units.   May contain multiple, representing different reporting areas. */
    public var snow: [SnowReport]
    /** List of all lifts at the resort with their current operational status,  type, and optional wait time information. */
    public var lifts: [Lift]
    /** List of all runs at the resort with their current status,  grooming information, and difficulty rating. */
    public var runs: [Run]
    /** List of all terrain parks at the resort with their current status,  condition notes, and list of features (jumps, boxes, rails, etc.) within them. */
    public var terrainParks: [TerrainPark]
    /** List of all parking lots at the resort with their current status and amenities. */
    public var parkingLots: [ParkingLot]
    /** List of all summer trails at the resort with their current status,  type (e.g. hiking, mountain biking), and optional difficulty rating. */
    public var summerTrails: [SummerTrail]
    public var hours: OperatingHours
    /** Weather entries: the resort-wide entry first (current + forecast), then  any per-area current-conditions entries. Empty when weather is disabled  or unavailable. */
    public var weather: [Weather]?
    /** Enabled webcams with the URLs of their current and last-daylight frames  plus thumbnails. Empty when the resort does not have webcams. */
    public var webcams: [Webcam]?
    /** All amenities at the resort — identical to `GET /api/v1/report/amenities`. */
    public var amenities: [Amenity]
    /** Trail-map summaries — identical to `GET /api/v1/report/trail-maps`.  Empty when the `trail_maps` feature is not enabled for the resort. */
    public var trailMaps: [TrailMapSummary]?
    /** Mobile-app banners, in display order. */
    public var appBanners: [MobileAppBanner]

    public init(resort: ResortInfo, status: Overview, snow: [SnowReport], lifts: [Lift], runs: [Run], terrainParks: [TerrainPark], parkingLots: [ParkingLot], summerTrails: [SummerTrail], hours: OperatingHours, weather: [Weather]? = nil, webcams: [Webcam]? = nil, amenities: [Amenity], trailMaps: [TrailMapSummary]? = nil, appBanners: [MobileAppBanner]) {
        self.resort = resort
        self.status = status
        self.snow = snow
        self.lifts = lifts
        self.runs = runs
        self.terrainParks = terrainParks
        self.parkingLots = parkingLots
        self.summerTrails = summerTrails
        self.hours = hours
        self.weather = weather
        self.webcams = webcams
        self.amenities = amenities
        self.trailMaps = trailMaps
        self.appBanners = appBanners
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case resort
        case status
        case snow
        case lifts
        case runs
        case terrainParks = "terrain_parks"
        case parkingLots = "parking_lots"
        case summerTrails = "summer_trails"
        case hours
        case weather
        case webcams
        case amenities
        case trailMaps = "trail_maps"
        case appBanners = "app_banners"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(resort, forKey: .resort)
        try container.encode(status, forKey: .status)
        try container.encode(snow, forKey: .snow)
        try container.encode(lifts, forKey: .lifts)
        try container.encode(runs, forKey: .runs)
        try container.encode(terrainParks, forKey: .terrainParks)
        try container.encode(parkingLots, forKey: .parkingLots)
        try container.encode(summerTrails, forKey: .summerTrails)
        try container.encode(hours, forKey: .hours)
        try container.encodeIfPresent(weather, forKey: .weather)
        try container.encodeIfPresent(webcams, forKey: .webcams)
        try container.encode(amenities, forKey: .amenities)
        try container.encodeIfPresent(trailMaps, forKey: .trailMaps)
        try container.encode(appBanners, forKey: .appBanners)
    }
}

