//
// CalendarDay.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Operating hours for a specific calendar date.   Represents the calculated open/close times for a single day, combining  information from recurring schedules and any single-day overrides. */
public struct CalendarDay: Sendable, Codable, Hashable {

    public static let opensAtRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^([01]\\d|2[0-3]):[0-5]\\d$/")
    public static let closesAtRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^([01]\\d|2[0-3]):[0-5]\\d$/")
    /** Calendar date (YYYY-MM-DD). */
    public var date: Date
    /** Day of the week. */
    public var dayOfWeek: DayOfWeek
    /** Whether the resort is open on this day. */
    public var isOpen: Bool
    /** Opening time in 24-hour format (HH:MM), in resort's local timezone.  `null` if closed on this day. */
    public var opensAt: String?
    /** Closing time in 24-hour format (HH:MM), in resort's local timezone.  `null` if closed on this day. */
    public var closesAt: String?
    public var closureReason: ClosureReason?
    /** Special event for this day. */
    public var specialEvent: String?

    public init(date: Date, dayOfWeek: DayOfWeek, isOpen: Bool, opensAt: String? = nil, closesAt: String? = nil, closureReason: ClosureReason? = nil, specialEvent: String? = nil) {
        self.date = date
        self.dayOfWeek = dayOfWeek
        self.isOpen = isOpen
        self.opensAt = opensAt
        self.closesAt = closesAt
        self.closureReason = closureReason
        self.specialEvent = specialEvent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case dayOfWeek = "day_of_week"
        case isOpen = "is_open"
        case opensAt = "opens_at"
        case closesAt = "closes_at"
        case closureReason = "closure_reason"
        case specialEvent = "special_event"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(date, forKey: .date)
        try container.encode(dayOfWeek, forKey: .dayOfWeek)
        try container.encode(isOpen, forKey: .isOpen)
        try container.encodeIfPresent(opensAt, forKey: .opensAt)
        try container.encodeIfPresent(closesAt, forKey: .closesAt)
        try container.encodeIfPresent(closureReason, forKey: .closureReason)
        try container.encodeIfPresent(specialEvent, forKey: .specialEvent)
    }
}

