//
// ClosureReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Reason for unexpected closure */
public enum ClosureReason: String, Sendable, Codable, CaseIterable {
    case extremeCold = "extreme_cold"
    case highWinds = "high_winds"
    case snowConditions = "snow_conditions"
    case mechanicalIssues = "mechanical_issues"
}
