//
// CurrentWeather.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Current weather conditions with both metric and imperial units */
public struct CurrentWeather: Sendable, Codable, Hashable {

    /** Measurements in imperial units */
    public var imperial: CurrentWeatherImperial
    /** Measurements in metric units */
    public var metric: CurrentWeatherMetric
    /** Human-readable weather condition */
    public var condition: String
    /** Weather condition code */
    public var conditionCode: WeatherConditionCode
    /** Wind direction in degrees (0-360) */
    public var windDirection: Int?
    /** Wind direction as cardinal direction (N, NE, E, SE, S, SW, W, NW) */
    public var windDirectionCardinal: String?
    /** Timestamp of observation */
    public var timestamp: Date

    public init(imperial: CurrentWeatherImperial, metric: CurrentWeatherMetric, condition: String, conditionCode: WeatherConditionCode, windDirection: Int? = nil, windDirectionCardinal: String? = nil, timestamp: Date) {
        self.imperial = imperial
        self.metric = metric
        self.condition = condition
        self.conditionCode = conditionCode
        self.windDirection = windDirection
        self.windDirectionCardinal = windDirectionCardinal
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case imperial
        case metric
        case condition
        case conditionCode = "condition_code"
        case windDirection = "wind_direction"
        case windDirectionCardinal = "wind_direction_cardinal"
        case timestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(imperial, forKey: .imperial)
        try container.encode(metric, forKey: .metric)
        try container.encode(condition, forKey: .condition)
        try container.encode(conditionCode, forKey: .conditionCode)
        try container.encodeIfPresent(windDirection, forKey: .windDirection)
        try container.encodeIfPresent(windDirectionCardinal, forKey: .windDirectionCardinal)
        try container.encode(timestamp, forKey: .timestamp)
    }
}

