//
// CurrentWeatherMetric.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Current temperature and precipitation measurements in metric units */
public struct CurrentWeatherMetric: Sendable, Codable, Hashable {

    /** Temperature in Celsius */
    public var temperature: Int
    /** Feels like temperature in Celsius */
    public var feelsLike: Int
    /** Snowfall in centimeters */
    public var snowfall: Int?
    /** Precipitation in millimeters */
    public var precipitation: Int?
    /** Wind speed in km/h */
    public var windSpeed: Int
    /** Wind gust in km/h */
    public var windGust: Int?

    public init(temperature: Int, feelsLike: Int, snowfall: Int? = nil, precipitation: Int? = nil, windSpeed: Int, windGust: Int? = nil) {
        self.temperature = temperature
        self.feelsLike = feelsLike
        self.snowfall = snowfall
        self.precipitation = precipitation
        self.windSpeed = windSpeed
        self.windGust = windGust
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case temperature
        case feelsLike = "feels_like"
        case snowfall
        case precipitation
        case windSpeed = "wind_speed"
        case windGust = "wind_gust"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(temperature, forKey: .temperature)
        try container.encode(feelsLike, forKey: .feelsLike)
        try container.encodeIfPresent(snowfall, forKey: .snowfall)
        try container.encodeIfPresent(precipitation, forKey: .precipitation)
        try container.encode(windSpeed, forKey: .windSpeed)
        try container.encodeIfPresent(windGust, forKey: .windGust)
    }
}

