//
// DailyForecast.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Daily weather summary with both unit systems */
public struct DailyForecast: Sendable, Codable, Hashable {

    /** Date of forecast (YYYY-MM-DD format) */
    public var date: Date
    /** Measurements in imperial units */
    public var imperial: DailyForecastImperial
    /** Measurements in metric units */
    public var metric: DailyForecastMetric
    /** Human-readable condition */
    public var condition: String
    /** Condition code */
    public var conditionCode: WeatherConditionCode
    /** Probability of precipitation (0-100%) */
    public var precipitationProbability: Int?
    /** Sunrise time */
    public var sunrise: Date
    /** Sunset time */
    public var sunset: Date

    public init(date: Date, imperial: DailyForecastImperial, metric: DailyForecastMetric, condition: String, conditionCode: WeatherConditionCode, precipitationProbability: Int? = nil, sunrise: Date, sunset: Date) {
        self.date = date
        self.imperial = imperial
        self.metric = metric
        self.condition = condition
        self.conditionCode = conditionCode
        self.precipitationProbability = precipitationProbability
        self.sunrise = sunrise
        self.sunset = sunset
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case imperial
        case metric
        case condition
        case conditionCode = "condition_code"
        case precipitationProbability = "precipitation_probability"
        case sunrise
        case sunset
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(date, forKey: .date)
        try container.encode(imperial, forKey: .imperial)
        try container.encode(metric, forKey: .metric)
        try container.encode(condition, forKey: .condition)
        try container.encode(conditionCode, forKey: .conditionCode)
        try container.encodeIfPresent(precipitationProbability, forKey: .precipitationProbability)
        try container.encode(sunrise, forKey: .sunrise)
        try container.encode(sunset, forKey: .sunset)
    }
}

