//
// DailyForecastImperial.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Daily forecast measurements in imperial units */
public struct DailyForecastImperial: Sendable, Codable, Hashable {

    /** High temperature in Fahrenheit */
    public var temperatureHigh: Int
    /** Low temperature in Fahrenheit */
    public var temperatureLow: Int
    /** Total snowfall expected in inches */
    public var snowfallTotal: Int?
    /** Total precipitation expected in inches */
    public var precipitationTotal: Int?
    /** Maximum wind speed in mph */
    public var windSpeedMax: Int?
    /** Maximum wind gust in mph */
    public var windGustMax: Int?

    public init(temperatureHigh: Int, temperatureLow: Int, snowfallTotal: Int? = nil, precipitationTotal: Int? = nil, windSpeedMax: Int? = nil, windGustMax: Int? = nil) {
        self.temperatureHigh = temperatureHigh
        self.temperatureLow = temperatureLow
        self.snowfallTotal = snowfallTotal
        self.precipitationTotal = precipitationTotal
        self.windSpeedMax = windSpeedMax
        self.windGustMax = windGustMax
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case temperatureHigh = "temperature_high"
        case temperatureLow = "temperature_low"
        case snowfallTotal = "snowfall_total"
        case precipitationTotal = "precipitation_total"
        case windSpeedMax = "wind_speed_max"
        case windGustMax = "wind_gust_max"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(temperatureHigh, forKey: .temperatureHigh)
        try container.encode(temperatureLow, forKey: .temperatureLow)
        try container.encodeIfPresent(snowfallTotal, forKey: .snowfallTotal)
        try container.encodeIfPresent(precipitationTotal, forKey: .precipitationTotal)
        try container.encodeIfPresent(windSpeedMax, forKey: .windSpeedMax)
        try container.encodeIfPresent(windGustMax, forKey: .windGustMax)
    }
}

