//
// DayOfWeek.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum DayOfWeek: String, Sendable, Codable, CaseIterable {
    case sunday = "Sunday"
    case monday = "Monday"
    case tuesday = "Tuesday"
    case wednesday = "Wednesday"
    case thursday = "Thursday"
    case friday = "Friday"
    case saturday = "Saturday"
}
