//
// EntityImage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A single image attached to a resort entity, with a client-supplied ThumbHash  for rendering a blurred placeholder while the full image loads. */
public struct EntityImage: Sendable, Codable, Hashable {

    /** Full public URL to the image. */
    public var url: String
    /** Base64-encoded ThumbHash for placeholder rendering. */
    public var thumbHash: String

    public init(url: String, thumbHash: String) {
        self.url = url
        self.thumbHash = thumbHash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case thumbHash = "thumb_hash"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(url, forKey: .url)
        try container.encode(thumbHash, forKey: .thumbHash)
    }
}

