//
// FeatureType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Type of terrain park feature. */
public enum FeatureType: String, Sendable, Codable, CaseIterable {
    case jump = "jump"
    case box = "box"
    case rail = "rail"
    case other = "other"
}
