//
// FullReport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The all-in-one endpoint containing the full report — resort information, current status,  runs, lifts, snow, terrain parks, summer trails, hours, and weather. */
public struct FullReport: Sendable, Codable, Hashable {

    public var resort: ResortInfo
    public var status: Overview
    /** Provides current snow conditions including base depth, surface conditions,  and snowfall totals in both metric and imperial units.   May contain multiple, representing different reporting areas. */
    public var snow: [SnowReport]
    /** List of all lifts at the resort with their current operational status,  type, and optional wait time information. */
    public var lifts: [Lift]
    /** List of all runs at the resort with their current status,  grooming information, and difficulty rating. */
    public var runs: [Run]
    /** List of all terrain parks at the resort with their current status,  condition notes, and list of features (jumps, boxes, rails, etc.) within them. */
    public var terrainParks: [TerrainPark]
    /** List of all summer trails at the resort with their current status,  type (e.g. hiking, mountain biking), and optional difficulty rating. */
    public var summerTrails: [SummerTrail]
    public var hours: OperatingHours
    public var weather: Weather?

    public init(resort: ResortInfo, status: Overview, snow: [SnowReport], lifts: [Lift], runs: [Run], terrainParks: [TerrainPark], summerTrails: [SummerTrail], hours: OperatingHours, weather: Weather? = nil) {
        self.resort = resort
        self.status = status
        self.snow = snow
        self.lifts = lifts
        self.runs = runs
        self.terrainParks = terrainParks
        self.summerTrails = summerTrails
        self.hours = hours
        self.weather = weather
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case resort
        case status
        case snow
        case lifts
        case runs
        case terrainParks = "terrain_parks"
        case summerTrails = "summer_trails"
        case hours
        case weather
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(resort, forKey: .resort)
        try container.encode(status, forKey: .status)
        try container.encode(snow, forKey: .snow)
        try container.encode(lifts, forKey: .lifts)
        try container.encode(runs, forKey: .runs)
        try container.encode(terrainParks, forKey: .terrainParks)
        try container.encode(summerTrails, forKey: .summerTrails)
        try container.encode(hours, forKey: .hours)
        try container.encodeIfPresent(weather, forKey: .weather)
    }
}

