//
// GeoBounds.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Lat/lng bounding box and centroid for a trail map&#39;s georeferenced area. */
public struct GeoBounds: Sendable, Codable, Hashable {

    public var minLat: Double
    public var maxLat: Double
    public var minLng: Double
    public var maxLng: Double
    public var center: GeoPoint

    public init(minLat: Double, maxLat: Double, minLng: Double, maxLng: Double, center: GeoPoint) {
        self.minLat = minLat
        self.maxLat = maxLat
        self.minLng = minLng
        self.maxLng = maxLng
        self.center = center
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case minLat = "min_lat"
        case maxLat = "max_lat"
        case minLng = "min_lng"
        case maxLng = "max_lng"
        case center
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(minLat, forKey: .minLat)
        try container.encode(maxLat, forKey: .maxLat)
        try container.encode(minLng, forKey: .minLng)
        try container.encode(maxLng, forKey: .maxLng)
        try container.encode(center, forKey: .center)
    }
}

