//
// GeoControlPoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GeoControlPoint: Sendable, Codable, Hashable {

    public var pixelX: Double
    public var pixelY: Double
    public var lat: Double
    public var lng: Double

    public init(pixelX: Double, pixelY: Double, lat: Double, lng: Double) {
        self.pixelX = pixelX
        self.pixelY = pixelY
        self.lat = lat
        self.lng = lng
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pixelX = "pixel_x"
        case pixelY = "pixel_y"
        case lat
        case lng
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pixelX, forKey: .pixelX)
        try container.encode(pixelY, forKey: .pixelY)
        try container.encode(lat, forKey: .lat)
        try container.encode(lng, forKey: .lng)
    }
}

