//
// GeometryMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum GeometryMode: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case path = "path"
    case polygon = "polygon"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension GeometryMode: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
