//
// HourlyForecast.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Hourly weather forecast entry with both metric and imperial units */
public struct HourlyForecast: Sendable, Codable, Hashable {

    /** Forecast timestamp */
    public var timestamp: Date
    /** Measurements in imperial units */
    public var imperial: HourlyForecastImperial
    /** Measurements in metric units */
    public var metric: HourlyForecastMetric
    /** Human-readable condition */
    public var condition: String
    /** Weather condition code */
    public var conditionCode: WeatherConditionCode
    /** Probability of precipitation (0-100%) */
    public var precipitationProbability: Int?

    public init(timestamp: Date, imperial: HourlyForecastImperial, metric: HourlyForecastMetric, condition: String, conditionCode: WeatherConditionCode, precipitationProbability: Int? = nil) {
        self.timestamp = timestamp
        self.imperial = imperial
        self.metric = metric
        self.condition = condition
        self.conditionCode = conditionCode
        self.precipitationProbability = precipitationProbability
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timestamp
        case imperial
        case metric
        case condition
        case conditionCode = "condition_code"
        case precipitationProbability = "precipitation_probability"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(timestamp, forKey: .timestamp)
        try container.encode(imperial, forKey: .imperial)
        try container.encode(metric, forKey: .metric)
        try container.encode(condition, forKey: .condition)
        try container.encode(conditionCode, forKey: .conditionCode)
        try container.encodeIfPresent(precipitationProbability, forKey: .precipitationProbability)
    }
}

