//
// Lift.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Represents a single lift at the resort with its current operational status,  type, and optional wait time information. */
public struct Lift: Sendable, Codable, Hashable {

    /** Unique identifier for the lift. */
    public var uuid: String
    /** Display name of the lift. */
    public var name: String
    /** URL-friendly name of the lift. */
    public var slug: String
    /** Optional lift number. */
    public var number: Int?
    /** Type of lift (e.g. gondola, quad). */
    public var liftType: LiftType
    /** Whether this is a high-speed/detachable lift. */
    public var highSpeed: Bool
    /** Whether the lift has a bubble/cover for weather protection. */
    public var bubble: Bool
    /** Whether the lift has heated seats. */
    public var heated: Bool
    /** Estimated travel time in minutes. */
    public var travelTime: Double?
    /** Length of the lift in feet. */
    public var lengthFt: Int?
    /** Length of the lift in meters. */
    public var lengthM: Int?
    /** Vertical rise of the lift in feet. */
    public var verticalRiseFt: Int?
    /** Vertical rise of the lift in meters. */
    public var verticalRiseM: Int?
    /** Current operational status (open, closed, on_hold, or unknown). */
    public var status: LiftStatus
    /** Current estimated wait time in minutes, if available. */
    public var waitTimeMinutes: Int64?
    /** Today's scheduled opening time in 24-hour format (HH:MM), in resort's local timezone.  `null` if the lift has no scheduled hours for today. */
    public var opensAt: String?
    /** Today's scheduled closing time in 24-hour format (HH:MM), in resort's local timezone.  `null` if the lift has no scheduled hours for today. */
    public var closesAt: String?
    /** UUID of the area this lift belongs to, if assigned. */
    public var areaUuid: String?
    /** Name of the area this lift belongs to, if assigned. */
    public var areaName: String?
    /** Display order of the area this lift belongs to, if assigned, for sorting purposes. */
    public var areaDisplayOrder: Int?
    /** When this lift's information was last updated. */
    public var updatedAt: Date
    /** Images attached to this lift, ordered for display. Each includes a  ThumbHash for rendering a blurred placeholder while the image loads. */
    public var images: [EntityImage]?

    public init(uuid: String, name: String, slug: String, number: Int? = nil, liftType: LiftType, highSpeed: Bool, bubble: Bool, heated: Bool, travelTime: Double? = nil, lengthFt: Int? = nil, lengthM: Int? = nil, verticalRiseFt: Int? = nil, verticalRiseM: Int? = nil, status: LiftStatus, waitTimeMinutes: Int64? = nil, opensAt: String? = nil, closesAt: String? = nil, areaUuid: String? = nil, areaName: String? = nil, areaDisplayOrder: Int? = nil, updatedAt: Date, images: [EntityImage]? = nil) {
        self.uuid = uuid
        self.name = name
        self.slug = slug
        self.number = number
        self.liftType = liftType
        self.highSpeed = highSpeed
        self.bubble = bubble
        self.heated = heated
        self.travelTime = travelTime
        self.lengthFt = lengthFt
        self.lengthM = lengthM
        self.verticalRiseFt = verticalRiseFt
        self.verticalRiseM = verticalRiseM
        self.status = status
        self.waitTimeMinutes = waitTimeMinutes
        self.opensAt = opensAt
        self.closesAt = closesAt
        self.areaUuid = areaUuid
        self.areaName = areaName
        self.areaDisplayOrder = areaDisplayOrder
        self.updatedAt = updatedAt
        self.images = images
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case name
        case slug
        case number
        case liftType = "lift_type"
        case highSpeed = "high_speed"
        case bubble
        case heated
        case travelTime = "travel_time"
        case lengthFt = "length_ft"
        case lengthM = "length_m"
        case verticalRiseFt = "vertical_rise_ft"
        case verticalRiseM = "vertical_rise_m"
        case status
        case waitTimeMinutes = "wait_time_minutes"
        case opensAt = "opens_at"
        case closesAt = "closes_at"
        case areaUuid = "area_uuid"
        case areaName = "area_name"
        case areaDisplayOrder = "area_display_order"
        case updatedAt = "updated_at"
        case images
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(name, forKey: .name)
        try container.encode(slug, forKey: .slug)
        try container.encodeIfPresent(number, forKey: .number)
        try container.encode(liftType, forKey: .liftType)
        try container.encode(highSpeed, forKey: .highSpeed)
        try container.encode(bubble, forKey: .bubble)
        try container.encode(heated, forKey: .heated)
        try container.encodeIfPresent(travelTime, forKey: .travelTime)
        try container.encodeIfPresent(lengthFt, forKey: .lengthFt)
        try container.encodeIfPresent(lengthM, forKey: .lengthM)
        try container.encodeIfPresent(verticalRiseFt, forKey: .verticalRiseFt)
        try container.encodeIfPresent(verticalRiseM, forKey: .verticalRiseM)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(waitTimeMinutes, forKey: .waitTimeMinutes)
        try container.encodeIfPresent(opensAt, forKey: .opensAt)
        try container.encodeIfPresent(closesAt, forKey: .closesAt)
        try container.encodeIfPresent(areaUuid, forKey: .areaUuid)
        try container.encodeIfPresent(areaName, forKey: .areaName)
        try container.encodeIfPresent(areaDisplayOrder, forKey: .areaDisplayOrder)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(images, forKey: .images)
    }
}


extension Lift: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if liftType == .unknownDefaultOpenApi { return true }
        if status == .unknownDefaultOpenApi { return true }
        return false
    }
}
