//
// LiftType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Type of ski lift */
public enum LiftType: String, Sendable, Codable, CaseIterable {
    case gondola = "gondola"
    case tram = "tram"
    case eightPack = "eight_pack"
    case sixPack = "six_pack"
    case quad = "quad"
    case triple = "triple"
    case double = "double"
    case magicCarpet = "magic_carpet"
    case tBar = "t_bar"
    case platter = "platter"
    case ropeTow = "rope_tow"
    case funicular = "funicular"
    case other = "other"
}
