//
// Lift.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Represents a single lift at the resort with its current operational status,  type, and optional wait time information. */
public struct Lift: Sendable, Codable, Hashable {

    /** Unique identifier for the lift. */
    public var uuid: String
    /** Display name of the lift. */
    public var name: String
    /** URL-friendly name of the lift. */
    public var slug: String
    /** Optional lift number. */
    public var number: Int?
    /** Type of lift (e.g. gondola, quad). */
    public var liftType: LiftType
    /** Whether this is a high-speed/detachable lift. */
    public var highSpeed: Bool
    /** Whether the lift has a bubble/cover for weather protection. */
    public var bubble: Bool
    /** Whether the lift has heated seats. */
    public var heated: Bool
    /** Current operational status (open, closed, on_hold, or unknown). */
    public var status: LiftStatus
    /** Current estimated wait time in minutes, if available. */
    public var waitTimeMinutes: Int64?
    /** UUID of the area this lift belongs to, if assigned. */
    public var areaUuid: String?
    /** Name of the area this lift belongs to, if assigned. */
    public var areaName: String?
    /** Display order of the area this lift belongs to, if assigned, for sorting purposes. */
    public var areaDisplayOrder: Int?
    /** When this lift's information was last updated. */
    public var updatedAt: Date

    public init(uuid: String, name: String, slug: String, number: Int? = nil, liftType: LiftType, highSpeed: Bool, bubble: Bool, heated: Bool, status: LiftStatus, waitTimeMinutes: Int64? = nil, areaUuid: String? = nil, areaName: String? = nil, areaDisplayOrder: Int? = nil, updatedAt: Date) {
        self.uuid = uuid
        self.name = name
        self.slug = slug
        self.number = number
        self.liftType = liftType
        self.highSpeed = highSpeed
        self.bubble = bubble
        self.heated = heated
        self.status = status
        self.waitTimeMinutes = waitTimeMinutes
        self.areaUuid = areaUuid
        self.areaName = areaName
        self.areaDisplayOrder = areaDisplayOrder
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case name
        case slug
        case number
        case liftType = "lift_type"
        case highSpeed = "high_speed"
        case bubble
        case heated
        case status
        case waitTimeMinutes = "wait_time_minutes"
        case areaUuid = "area_uuid"
        case areaName = "area_name"
        case areaDisplayOrder = "area_display_order"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(name, forKey: .name)
        try container.encode(slug, forKey: .slug)
        try container.encodeIfPresent(number, forKey: .number)
        try container.encode(liftType, forKey: .liftType)
        try container.encode(highSpeed, forKey: .highSpeed)
        try container.encode(bubble, forKey: .bubble)
        try container.encode(heated, forKey: .heated)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(waitTimeMinutes, forKey: .waitTimeMinutes)
        try container.encodeIfPresent(areaUuid, forKey: .areaUuid)
        try container.encodeIfPresent(areaName, forKey: .areaName)
        try container.encodeIfPresent(areaDisplayOrder, forKey: .areaDisplayOrder)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

