//
// LiftStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Operational status of a ski lift. */
public enum LiftStatus: String, Sendable, Codable, CaseIterable {
    case `open` = "open"
    case closed = "closed"
    case onHold = "on_hold"
    case unknown = "unknown"
}
