//
// MarkerIcon.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum MarkerIcon: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case restaurant = "restaurant"
    case coffee = "coffee"
    case bar = "bar"
    case water = "water"
    case skiSchool = "ski_school"
    case rentalShop = "rental_shop"
    case tubing = "tubing"
    case daycare = "daycare"
    case ticketing = "ticketing"
    case lodge = "lodge"
    case hotel = "hotel"
    case restroom = "restroom"
    case lockers = "lockers"
    case firstAid = "first_aid"
    case parking = "parking"
    case bus = "bus"
    case info = "info"
    case help = "help"
    case phone = "phone"
    case retail = "retail"
    case atm = "atm"
    case star = "star"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension MarkerIcon: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
