//
// MobileAppBanner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A banner shown in the mobile app. */
public struct MobileAppBanner: Sendable, Codable, Hashable {

    public var title: String
    public var uuid: String
    public var subtitle: String
    /** Full public URL of the banner image. */
    public var image: String
    /** Destination URL opened when the banner is tapped. */
    public var url: String

    public init(title: String, uuid: String, subtitle: String, image: String, url: String) {
        self.title = title
        self.uuid = uuid
        self.subtitle = subtitle
        self.image = image
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case uuid
        case subtitle
        case image
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(subtitle, forKey: .subtitle)
        try container.encode(image, forKey: .image)
        try container.encode(url, forKey: .url)
    }
}

