//
// MobileAppBanner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A banner shown in the mobile app. */
public struct MobileAppBanner: Sendable, Codable, Hashable {

    public var title: String
    public var uuid: String
    public var subtitle: String
    /** Full public URL of the banner image. */
    public var imageUrl: String
    /** Destination URL opened when the banner is tapped. */
    public var url: String
    /** Base64-encoded ThumbHash of the banner image, for rendering a blurred  placeholder while the full image loads. */
    public var thumbHash: String

    public init(title: String, uuid: String, subtitle: String, imageUrl: String, url: String, thumbHash: String) {
        self.title = title
        self.uuid = uuid
        self.subtitle = subtitle
        self.imageUrl = imageUrl
        self.url = url
        self.thumbHash = thumbHash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case uuid
        case subtitle
        case imageUrl = "image_url"
        case url
        case thumbHash = "thumb_hash"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(subtitle, forKey: .subtitle)
        try container.encode(imageUrl, forKey: .imageUrl)
        try container.encode(url, forKey: .url)
        try container.encode(thumbHash, forKey: .thumbHash)
    }
}

