//
// MobileAppResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Aggregated mobile-app data for the resort. New mobile-app surface area is  added as additional fields on this response. */
public struct MobileAppResponse: Sendable, Codable, Hashable {

    /** Banners shown in the mobile app, in display order. */
    public var banners: [MobileAppBanner]

    public init(banners: [MobileAppBanner]) {
        self.banners = banners
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case banners
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(banners, forKey: .banners)
    }
}

