//
// OperatingHours.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Resort&#39;s operating hours, including the recurring schedule, and list of individual calendar days. */
public struct OperatingHours: Sendable, Codable, Hashable {

    /** Recurring operating schedules currently in effect or upcoming.  Excludes single-day overrides and past schedules. */
    public var schedules: [Schedule]
    /** List of all days the resort is open (or a closure override).  Ordered chronologically, spanning from the earliest scheduled date  to the latest scheduled date in the currently defined operating hours. */
    public var calendarDays: [CalendarDay]
    /** Per-amenity operating schedules. Only included when amenity hours are configured. */
    public var amenitySchedules: [AmenitySchedule]

    public init(schedules: [Schedule], calendarDays: [CalendarDay], amenitySchedules: [AmenitySchedule]) {
        self.schedules = schedules
        self.calendarDays = calendarDays
        self.amenitySchedules = amenitySchedules
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schedules
        case calendarDays = "calendar_days"
        case amenitySchedules = "amenity_schedules"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(schedules, forKey: .schedules)
        try container.encode(calendarDays, forKey: .calendarDays)
        try container.encode(amenitySchedules, forKey: .amenitySchedules)
    }
}

