//
// OverviewRuns.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Run statistics: open/groomed/total counts, open/total acres, and last-updated timestamp. */
public struct OverviewRuns: Sendable, Codable, Hashable {

    /** Number of runs currently open.  Not included if the runs status feature is disabled. */
    public var `open`: Int64?
    /** Number of runs groomed within the last 24 hours.  Not included if the runs grooming feature is disabled. */
    public var groomed: Int64?
    /** Total number of runs at the resort. */
    public var total: Int64
    /** Total acres of open runs.  Not included if acres are not tracked or the runs status feature is disabled. */
    public var openAcres: Int64?
    /** Total acres of all runs.  Not included if acres are not tracked. */
    public var totalAcres: Int64?
    /** When the most recent update to run status was made. */
    public var updatedAt: Date

    public init(`open`: Int64? = nil, groomed: Int64? = nil, total: Int64, openAcres: Int64? = nil, totalAcres: Int64? = nil, updatedAt: Date) {
        self.`open` = `open`
        self.groomed = groomed
        self.total = total
        self.openAcres = openAcres
        self.totalAcres = totalAcres
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case `open` = "open"
        case groomed
        case total
        case openAcres = "open_acres"
        case totalAcres = "total_acres"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(`open`, forKey: .`open`)
        try container.encodeIfPresent(groomed, forKey: .groomed)
        try container.encode(total, forKey: .total)
        try container.encodeIfPresent(openAcres, forKey: .openAcres)
        try container.encodeIfPresent(totalAcres, forKey: .totalAcres)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

