//
// Overview.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Provides a snapshot of the resort&#39;s current operational state including  today&#39;s scheduled hours (calculated from operating hour rules), run/lift  overview counts, the current season, and written news. */
public struct Overview: Sendable, Codable, Hashable {

    /** Current operational status of the resort (open or closed).  This is calculated based on the current time relative to today's scheduled hours. */
    public var status: ResortStatus
    /** Today's scheduled opening time in 24-hour format (HH:MM).  `null` if the resort is not scheduled to open today. */
    public var opensAt: String?
    /** Today's scheduled closing time in 24-hour format (HH:MM).  `null` if the resort is not scheduled to open today. */
    public var closesAt: String?
    /** Current operating season (winter, summer, or closed/off-season). */
    public var season: SeasonType
    /** Written news — daily update, announcements, etc. */
    public var news: OverviewNews
    /** Run statistics: counts, acres, and last-updated timestamp. */
    public var runs: OverviewRuns
    /** Lift statistics: counts and last-updated timestamp. */
    public var lifts: OverviewLifts
    /** Summer trail statistics: counts and last-updated timestamp. */
    public var summerTrails: OverviewSummerTrails
    /** Terrain park statistics: counts and last-updated timestamp. */
    public var terrainParks: OverviewTerrainParks

    public init(status: ResortStatus, opensAt: String? = nil, closesAt: String? = nil, season: SeasonType, news: OverviewNews, runs: OverviewRuns, lifts: OverviewLifts, summerTrails: OverviewSummerTrails, terrainParks: OverviewTerrainParks) {
        self.status = status
        self.opensAt = opensAt
        self.closesAt = closesAt
        self.season = season
        self.news = news
        self.runs = runs
        self.lifts = lifts
        self.summerTrails = summerTrails
        self.terrainParks = terrainParks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case opensAt = "opens_at"
        case closesAt = "closes_at"
        case season
        case news
        case runs
        case lifts
        case summerTrails = "summer_trails"
        case terrainParks = "terrain_parks"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(opensAt, forKey: .opensAt)
        try container.encodeIfPresent(closesAt, forKey: .closesAt)
        try container.encode(season, forKey: .season)
        try container.encode(news, forKey: .news)
        try container.encode(runs, forKey: .runs)
        try container.encode(lifts, forKey: .lifts)
        try container.encode(summerTrails, forKey: .summerTrails)
        try container.encode(terrainParks, forKey: .terrainParks)
    }
}


extension Overview: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if status == .unknownDefaultOpenApi { return true }
        if season == .unknownDefaultOpenApi { return true }
        return false
    }
}
