//
// OverviewTerrainParks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Terrain park statistics: open/total counts and last-updated timestamp. */
public struct OverviewTerrainParks: Sendable, Codable, Hashable {

    /** Number of terrain parks currently open.  Not included if the terrain parks status feature is disabled. */
    public var `open`: Int64?
    /** Total number of terrain parks at the resort. */
    public var total: Int64
    /** When the most recent update to terrain park status was made. */
    public var updatedAt: Date

    public init(`open`: Int64? = nil, total: Int64, updatedAt: Date) {
        self.`open` = `open`
        self.total = total
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case `open` = "open"
        case total
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(`open`, forKey: .`open`)
        try container.encode(total, forKey: .total)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

