//
// Overview.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Provides a snapshot of the resort&#39;s current operational state including  today&#39;s scheduled hours (calculated from operating hour rules), run/lift  overview counts, the current season, and written news. */
public struct Overview: Sendable, Codable, Hashable {

    /** Current operational status of the resort (open or closed).  This is calculated based on the current time relative to today's scheduled hours. */
    public var status: ResortStatus
    /** Today's scheduled opening time in 24-hour format (HH:MM).  `null` if the resort is not scheduled to open today. */
    public var opensAt: String?
    /** Today's scheduled closing time in 24-hour format (HH:MM).  `null` if the resort is not scheduled to open today. */
    public var closesAt: String?
    /** Current operating season (winter, summer, or closed/off-season). */
    public var season: SeasonType
    /** Written news — daily update, announcements, etc. (Markdown source). */
    public var news: String
    /** Written news — daily update, announcements, etc. (rendered as HTML from Markdown). */
    public var newsHtml: String
    /** When the written news was last updated. */
    public var newsUpdatedAt: Date
    /** Number of runs currently open.  Not included if the runs status feature is disabled. */
    public var openRuns: Int64?
    /** Number of runs groomed within the last 24 hours.  Not included if the runs grooming feature is disabled. */
    public var groomedRuns: Int64?
    /** Total number of runs at the resort. */
    public var totalRuns: Int64
    /** When the most recent update to run status was made. */
    public var runsUpdatedAt: Date
    /** Number of lifts currently open.  Not included if the lifts status feature is disabled. */
    public var openLifts: Int64?
    /** Total number of lifts at the resort. */
    public var totalLifts: Int64
    /** When the most recent update to lift status was made. */
    public var liftsUpdatedAt: Date
    /** Number of summer trails currently open.  Not included if the summer trails status feature is disabled. */
    public var openSummerTrails: Int64?
    /** Total number of summer trails at the resort. */
    public var totalSummerTrails: Int64
    /** When the most recent update to summer trail status was made. */
    public var summerTrailsUpdatedAt: Date
    /** Number of terrain parks currently open.  Not included if the terrain parks status feature is disabled. */
    public var openTerrainParks: Int64?
    /** Total number of terrain parks at the resort. */
    public var totalTerrainParks: Int64
    /** When the most recent update to terrain park status was made. */
    public var terrainParksUpdatedAt: Date

    public init(status: ResortStatus, opensAt: String? = nil, closesAt: String? = nil, season: SeasonType, news: String, newsHtml: String, newsUpdatedAt: Date, openRuns: Int64? = nil, groomedRuns: Int64? = nil, totalRuns: Int64, runsUpdatedAt: Date, openLifts: Int64? = nil, totalLifts: Int64, liftsUpdatedAt: Date, openSummerTrails: Int64? = nil, totalSummerTrails: Int64, summerTrailsUpdatedAt: Date, openTerrainParks: Int64? = nil, totalTerrainParks: Int64, terrainParksUpdatedAt: Date) {
        self.status = status
        self.opensAt = opensAt
        self.closesAt = closesAt
        self.season = season
        self.news = news
        self.newsHtml = newsHtml
        self.newsUpdatedAt = newsUpdatedAt
        self.openRuns = openRuns
        self.groomedRuns = groomedRuns
        self.totalRuns = totalRuns
        self.runsUpdatedAt = runsUpdatedAt
        self.openLifts = openLifts
        self.totalLifts = totalLifts
        self.liftsUpdatedAt = liftsUpdatedAt
        self.openSummerTrails = openSummerTrails
        self.totalSummerTrails = totalSummerTrails
        self.summerTrailsUpdatedAt = summerTrailsUpdatedAt
        self.openTerrainParks = openTerrainParks
        self.totalTerrainParks = totalTerrainParks
        self.terrainParksUpdatedAt = terrainParksUpdatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case opensAt = "opens_at"
        case closesAt = "closes_at"
        case season
        case news
        case newsHtml = "news_html"
        case newsUpdatedAt = "news_updated_at"
        case openRuns = "open_runs"
        case groomedRuns = "groomed_runs"
        case totalRuns = "total_runs"
        case runsUpdatedAt = "runs_updated_at"
        case openLifts = "open_lifts"
        case totalLifts = "total_lifts"
        case liftsUpdatedAt = "lifts_updated_at"
        case openSummerTrails = "open_summer_trails"
        case totalSummerTrails = "total_summer_trails"
        case summerTrailsUpdatedAt = "summer_trails_updated_at"
        case openTerrainParks = "open_terrain_parks"
        case totalTerrainParks = "total_terrain_parks"
        case terrainParksUpdatedAt = "terrain_parks_updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(opensAt, forKey: .opensAt)
        try container.encodeIfPresent(closesAt, forKey: .closesAt)
        try container.encode(season, forKey: .season)
        try container.encode(news, forKey: .news)
        try container.encode(newsHtml, forKey: .newsHtml)
        try container.encode(newsUpdatedAt, forKey: .newsUpdatedAt)
        try container.encodeIfPresent(openRuns, forKey: .openRuns)
        try container.encodeIfPresent(groomedRuns, forKey: .groomedRuns)
        try container.encode(totalRuns, forKey: .totalRuns)
        try container.encode(runsUpdatedAt, forKey: .runsUpdatedAt)
        try container.encodeIfPresent(openLifts, forKey: .openLifts)
        try container.encode(totalLifts, forKey: .totalLifts)
        try container.encode(liftsUpdatedAt, forKey: .liftsUpdatedAt)
        try container.encodeIfPresent(openSummerTrails, forKey: .openSummerTrails)
        try container.encode(totalSummerTrails, forKey: .totalSummerTrails)
        try container.encode(summerTrailsUpdatedAt, forKey: .summerTrailsUpdatedAt)
        try container.encodeIfPresent(openTerrainParks, forKey: .openTerrainParks)
        try container.encode(totalTerrainParks, forKey: .totalTerrainParks)
        try container.encode(terrainParksUpdatedAt, forKey: .terrainParksUpdatedAt)
    }
}

