//
// OverviewNews.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Written news — daily update, announcements, etc. */
public struct OverviewNews: Sendable, Codable, Hashable {

    /** Raw Markdown source. */
    public var raw: String
    /** Rendered HTML (from Markdown). */
    public var html: String
    /** When the news was last updated. */
    public var updatedAt: Date

    public init(raw: String, html: String, updatedAt: Date) {
        self.raw = raw
        self.html = html
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case raw
        case html
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(raw, forKey: .raw)
        try container.encode(html, forKey: .html)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

