//
// ParkingLot.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Represents a parking lot at the resort with its current status and amenities. */
public struct ParkingLot: Sendable, Codable, Hashable {

    /** Unique identifier for the parking lot. */
    public var uuid: String
    /** Display name of the parking lot. */
    public var name: String
    /** URL-friendly name of the parking lot. */
    public var slug: String
    /** Current status (open, closed, or full). */
    public var status: ParkingLotStatus
    /** Maximum vehicle capacity, if set. */
    public var capacity: Int?
    /** Whether shuttle service is available from this lot. */
    public var shuttle: Bool
    /** Whether parking is paid/requires payment. */
    public var paid: Bool
    /** Whether a reservation is required to park here. */
    public var reservationRequired: Bool
    /** When this parking lot's information was last updated. */
    public var updatedAt: Date

    public init(uuid: String, name: String, slug: String, status: ParkingLotStatus, capacity: Int? = nil, shuttle: Bool, paid: Bool, reservationRequired: Bool, updatedAt: Date) {
        self.uuid = uuid
        self.name = name
        self.slug = slug
        self.status = status
        self.capacity = capacity
        self.shuttle = shuttle
        self.paid = paid
        self.reservationRequired = reservationRequired
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case name
        case slug
        case status
        case capacity
        case shuttle
        case paid
        case reservationRequired = "reservation_required"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(name, forKey: .name)
        try container.encode(slug, forKey: .slug)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(capacity, forKey: .capacity)
        try container.encode(shuttle, forKey: .shuttle)
        try container.encode(paid, forKey: .paid)
        try container.encode(reservationRequired, forKey: .reservationRequired)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

