//
// ParkingLotStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Operational status of a parking lot. */
public enum ParkingLotStatus: String, Sendable, Codable, CaseIterable {
    case `open` = "open"
    case closed = "closed"
    case full = "full"
}
