//
// PathUuid.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PathUuid: Sendable, Codable, Hashable {

    /** Resource UUID */
    public var uuid: String

    public init(uuid: String) {
        self.uuid = uuid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uuid, forKey: .uuid)
    }
}

