//
// PointMarker.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A point marker on a trail map, enriched with entity data where applicable. */
public enum PointMarker: Sendable, Codable, Hashable {
    case typePointMarkerOneOf(PointMarkerOneOf)
    case typePointMarkerOneOf1(PointMarkerOneOf1)
    case typePointMarkerOneOf2(PointMarkerOneOf2)
    case unknownDefaultOpenApi

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typePointMarkerOneOf(let value):
            try container.encode(value)
        case .typePointMarkerOneOf1(let value):
            try container.encode(value)
        case .typePointMarkerOneOf2(let value):
            try container.encode(value)
        case .unknownDefaultOpenApi:
            try container.encodeNil()
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(PointMarkerOneOf.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typePointMarkerOneOf(value)
        } else if let value = try? container.decode(PointMarkerOneOf1.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typePointMarkerOneOf1(value)
        } else if let value = try? container.decode(PointMarkerOneOf2.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typePointMarkerOneOf2(value)
        } else {
            self = .unknownDefaultOpenApi
        }
    }
}

