//
// PointMarkerOneOf1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PointMarkerOneOf1: Sendable, Codable, Hashable {

    public enum Kind: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case parkingLot = "parking_lot"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var uuid: String
    public var x: Double
    public var y: Double
    public var icon: MarkerIcon?
    public var color: String?
    public var parkingLot: ParkingLot?
    public var kind: Kind

    public init(uuid: String, x: Double, y: Double, icon: MarkerIcon? = nil, color: String? = nil, parkingLot: ParkingLot? = nil, kind: Kind) {
        self.uuid = uuid
        self.x = x
        self.y = y
        self.icon = icon
        self.color = color
        self.parkingLot = parkingLot
        self.kind = kind
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case x
        case y
        case icon
        case color
        case parkingLot = "parking_lot"
        case kind
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(x, forKey: .x)
        try container.encode(y, forKey: .y)
        try container.encodeIfPresent(icon, forKey: .icon)
        try container.encodeIfPresent(color, forKey: .color)
        try container.encodeIfPresent(parkingLot, forKey: .parkingLot)
        try container.encode(kind, forKey: .kind)
    }
}


extension PointMarkerOneOf1: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if icon == .unknownDefaultOpenApi { return true }
        if kind == .unknownDefaultOpenApi { return true }
        return false
    }
}
