//
// PowderAlerts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Guest powder alerts the resort offers. Both are &#x60;false&#x60; when the resort  doesn&#39;t offer powder alerts. */
public struct PowderAlerts: Sendable, Codable, Hashable {

    /** Guests can sign up for text alerts via  `POST /api/notifications/v1/text/powder/signup` on the resort's host. */
    public var text: Bool
    /** Guests can subscribe to push alerts in the resort's mobile app. */
    public var push: Bool

    public init(text: Bool, push: Bool) {
        self.text = text
        self.push = push
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case text
        case push
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(text, forKey: .text)
        try container.encode(push, forKey: .push)
    }
}

