//
// Region.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Region for an account */
public enum Region: String, Sendable, Codable, CaseIterable {
    case na = "na"
    case eu = "eu"
}
