//
// ResortStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Whether the resort is open right now, from today&#39;s scheduled hours. */
public enum ResortStatus: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case `open` = "open"
    case closed = "closed"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension ResortStatus: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
