//
// ResortInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Contains general information about the ski resort and its MtnManager account. */
public struct ResortInfo: Sendable, Codable, Hashable {

    /** Unique identifier for the resort. */
    public var uuid: String
    /** Display name of the resort. */
    public var name: String
    /** URL-friendly identifier for the resort, used in account subdomain. */
    public var slug: String
    /** IANA timezone identifier for the resort's local time. */
    public var timezone: String
    /** Region, affects difficulty icon style. */
    public var region: Region
    /** Preferred unit system for measurements (metric or imperial). */
    public var unitPreference: UnitPreference

    public init(uuid: String, name: String, slug: String, timezone: String, region: Region, unitPreference: UnitPreference) {
        self.uuid = uuid
        self.name = name
        self.slug = slug
        self.timezone = timezone
        self.region = region
        self.unitPreference = unitPreference
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case name
        case slug
        case timezone
        case region
        case unitPreference = "unit_preference"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(name, forKey: .name)
        try container.encode(slug, forKey: .slug)
        try container.encode(timezone, forKey: .timezone)
        try container.encode(region, forKey: .region)
        try container.encode(unitPreference, forKey: .unitPreference)
    }
}

