//
// ResortStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Current operational status of the resort. */
public enum ResortStatus: String, Sendable, Codable, CaseIterable {
    case `open` = "open"
    case closed = "closed"
}
