//
// RunDifficulty.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Difficulty rating for a ski run. */
public enum RunDifficulty: String, Sendable, Codable, CaseIterable {
    case beginner = "beginner"
    case intermediate = "intermediate"
    case advanced = "advanced"
    case expert = "expert"
    case terrainPark = "terrain_park"
}
