//
// RunStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Operational status of a ski run. */
public enum RunStatus: String, Sendable, Codable, CaseIterable {
    case `open` = "open"
    case closed = "closed"
    case unknown = "unknown"
}
