//
// SeasonPeriod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A season the resort&#39;s operating hours define: its type and its days. */
public struct SeasonPeriod: Sendable, Codable, Hashable {

    /** The season's type (`winter` or `summer`; never `closed`). */
    public var seasonType: SeasonType
    /** The season's first day (YYYY-MM-DD), in the resort's local timezone. */
    public var startsOn: Date
    /** The season's last day (YYYY-MM-DD), in the resort's local timezone. */
    public var endsOn: Date

    public init(seasonType: SeasonType, startsOn: Date, endsOn: Date) {
        self.seasonType = seasonType
        self.startsOn = startsOn
        self.endsOn = endsOn
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case seasonType = "season_type"
        case startsOn = "starts_on"
        case endsOn = "ends_on"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(seasonType, forKey: .seasonType)
        try container.encode(startsOn, forKey: .startsOn)
        try container.encode(endsOn, forKey: .endsOn)
    }
}


extension SeasonPeriod: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if seasonType == .unknownDefaultOpenApi { return true }
        return false
    }
}
