//
// SeasonType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A resort&#39;s season: winter or summer as its weekly operating hours say  (&#x60;OperatingHoursDb::season_type&#x60;), or closed outside every season (see  &#x60;utils::hours::season_on&#x60;). */
public enum SeasonType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case winter = "winter"
    case summer = "summer"
    case closed = "closed"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension SeasonType: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
