//
// SeasonType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Current operating season of the resort. */
public enum SeasonType: String, Sendable, Codable, CaseIterable {
    case winter = "winter"
    case summer = "summer"
    case closed = "closed"
}
