//
// SnowMetrics.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Contains snowfall totals for various time periods. Values are provided  in the unit indicated by the parent field name (cm or inches). */
public struct SnowMetrics: Sendable, Codable, Hashable {

    /** Snowfall during the overnight window (midnight to 9 AM local timezone). */
    public var overnight: Int
    /** Snowfall in the last 24 hours. */
    public var last24h: Int
    /** Snowfall in the last 48 hours. */
    public var last48h: Int
    /** Snowfall in the last 7 days. */
    public var last7days: Int
    /** Total snowfall for the current season. */
    public var seasonTotal: Int

    public init(overnight: Int, last24h: Int, last48h: Int, last7days: Int, seasonTotal: Int) {
        self.overnight = overnight
        self.last24h = last24h
        self.last48h = last48h
        self.last7days = last7days
        self.seasonTotal = seasonTotal
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case overnight
        case last24h = "last_24h"
        case last48h = "last_48h"
        case last7days = "last_7days"
        case seasonTotal = "season_total"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(overnight, forKey: .overnight)
        try container.encode(last24h, forKey: .last24h)
        try container.encode(last48h, forKey: .last48h)
        try container.encode(last7days, forKey: .last7days)
        try container.encode(seasonTotal, forKey: .seasonTotal)
    }
}

