//
// SummerTrailStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Operational status of a summer trail. */
public enum SummerTrailStatus: String, Sendable, Codable, CaseIterable {
    case `open` = "open"
    case closed = "closed"
    case unknown = "unknown"
}
