//
// SummerTrailDifficulty.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Difficulty rating for a summer trail. */
public enum SummerTrailDifficulty: String, Sendable, Codable, CaseIterable {
    case beginner = "beginner"
    case intermediate = "intermediate"
    case advanced = "advanced"
    case expert = "expert"
}
