//
// SummerTrailType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum SummerTrailType: String, Sendable, Codable, CaseIterable {
    case hiking = "hiking"
    case mountainBiking = "mountain_biking"
}
