//
// SummerTrail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Represents a single summer trail at the resort with its current status,  type (e.g. hiking, mountain biking), and optional difficulty rating. */
public struct SummerTrail: Sendable, Codable, Hashable {

    /** Unique identifier for the trail. */
    public var uuid: String
    /** Display name of the trail. */
    public var name: String
    /** URL-friendly name of the trail. */
    public var slug: String
    /** Optional trail number. */
    public var number: Int?
    /** Type of trail activity (e.g. hiking, mountain_biking). Can have multiple. */
    public var trailType: [SummerTrailType]
    public var difficulty: SummerTrailDifficulty?
    /** Current operational status (open, closed, or unknown). */
    public var status: SummerTrailStatus
    /** Notes about current conditions on this trail. */
    public var conditionNotes: String
    /** UUID of the area this trail belongs to, if assigned. */
    public var areaUuid: String?
    /** Name of the area this trail belongs to, if assigned. */
    public var areaName: String?
    /** Display order of the area this trail belongs to, if assigned, for sorting purposes. */
    public var areaDisplayOrder: Int?
    /** When this trail's information was last updated. */
    public var updatedAt: Date

    public init(uuid: String, name: String, slug: String, number: Int? = nil, trailType: [SummerTrailType], difficulty: SummerTrailDifficulty? = nil, status: SummerTrailStatus, conditionNotes: String, areaUuid: String? = nil, areaName: String? = nil, areaDisplayOrder: Int? = nil, updatedAt: Date) {
        self.uuid = uuid
        self.name = name
        self.slug = slug
        self.number = number
        self.trailType = trailType
        self.difficulty = difficulty
        self.status = status
        self.conditionNotes = conditionNotes
        self.areaUuid = areaUuid
        self.areaName = areaName
        self.areaDisplayOrder = areaDisplayOrder
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case name
        case slug
        case number
        case trailType = "trail_type"
        case difficulty
        case status
        case conditionNotes = "condition_notes"
        case areaUuid = "area_uuid"
        case areaName = "area_name"
        case areaDisplayOrder = "area_display_order"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(name, forKey: .name)
        try container.encode(slug, forKey: .slug)
        try container.encodeIfPresent(number, forKey: .number)
        try container.encode(trailType, forKey: .trailType)
        try container.encodeIfPresent(difficulty, forKey: .difficulty)
        try container.encode(status, forKey: .status)
        try container.encode(conditionNotes, forKey: .conditionNotes)
        try container.encodeIfPresent(areaUuid, forKey: .areaUuid)
        try container.encodeIfPresent(areaName, forKey: .areaName)
        try container.encodeIfPresent(areaDisplayOrder, forKey: .areaDisplayOrder)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

