//
// SurfaceCondition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Industry-standard letter codes describing snow surface conditions. */
public enum SurfaceCondition: String, Sendable, Codable, CaseIterable {
    case bs = "BS"
    case co = "CO"
    case fg = "FG"
    case hp = "HP"
    case ip = "IP"
    case `is` = "IS"
    case lg = "LG"
    case mg = "MG"
    case p = "P"
    case pp = "PP"
    case sc = "SC"
    case tc = "TC"
    case v = "V"
    case wg = "WG"
    case wp = "WP"
}
