//
// TerrainPark.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Represents a terrain park at the resort with its current status,  condition notes, and list of features (jumps, boxes, rails, etc.) within it. */
public struct TerrainPark: Sendable, Codable, Hashable {

    /** Unique identifier for the terrain park. */
    public var uuid: String
    /** Display name of the terrain park. */
    public var name: String
    /** URL-friendly name of the terrain park. */
    public var slug: String
    /** Optional terrain park number. */
    public var number: Int?
    /** Current operational status (open, closed, or unknown). */
    public var status: TerrainParkStatus
    /** Notes about current conditions in this terrain park. */
    public var conditionNotes: String
    /** UUID of the area this terrain park belongs to, if assigned. */
    public var areaUuid: String?
    /** Name of the area this terrain park belongs to, if assigned. */
    public var areaName: String?
    /** Display order of the area this terrain park belongs to, if assigned, for sorting purposes. */
    public var areaDisplayOrder: Int?
    /** Features within this terrain park (jumps, boxes, rails, etc.). */
    public var features: [TerrainParkFeature]
    /** When this terrain park or any of its features was last updated. */
    public var updatedAt: Date

    public init(uuid: String, name: String, slug: String, number: Int? = nil, status: TerrainParkStatus, conditionNotes: String, areaUuid: String? = nil, areaName: String? = nil, areaDisplayOrder: Int? = nil, features: [TerrainParkFeature], updatedAt: Date) {
        self.uuid = uuid
        self.name = name
        self.slug = slug
        self.number = number
        self.status = status
        self.conditionNotes = conditionNotes
        self.areaUuid = areaUuid
        self.areaName = areaName
        self.areaDisplayOrder = areaDisplayOrder
        self.features = features
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case name
        case slug
        case number
        case status
        case conditionNotes = "condition_notes"
        case areaUuid = "area_uuid"
        case areaName = "area_name"
        case areaDisplayOrder = "area_display_order"
        case features
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(name, forKey: .name)
        try container.encode(slug, forKey: .slug)
        try container.encodeIfPresent(number, forKey: .number)
        try container.encode(status, forKey: .status)
        try container.encode(conditionNotes, forKey: .conditionNotes)
        try container.encodeIfPresent(areaUuid, forKey: .areaUuid)
        try container.encodeIfPresent(areaName, forKey: .areaName)
        try container.encodeIfPresent(areaDisplayOrder, forKey: .areaDisplayOrder)
        try container.encode(features, forKey: .features)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

