//
// TerrainParkFeature.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Represents a single feature within a terrain park (jump, box, rail, etc.)  with its current status and size rating. */
public struct TerrainParkFeature: Sendable, Codable, Hashable {

    /** Unique identifier for the feature. */
    public var uuid: String
    /** Display name of the feature. */
    public var name: String
    /** URL-friendly name of the run. */
    public var slug: String
    /** Optional feature number. */
    public var number: Int?
    /** Type of feature (jump, box, rail, other). */
    public var featureType: FeatureType
    public var size: FeatureSize?
    /** Current operational status (open, closed, or unknown).  `unknown` unless the terrain park feature status is enabled. */
    public var status: TerrainParkFeatureStatus

    public init(uuid: String, name: String, slug: String, number: Int? = nil, featureType: FeatureType, size: FeatureSize? = nil, status: TerrainParkFeatureStatus) {
        self.uuid = uuid
        self.name = name
        self.slug = slug
        self.number = number
        self.featureType = featureType
        self.size = size
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case name
        case slug
        case number
        case featureType = "feature_type"
        case size
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(name, forKey: .name)
        try container.encode(slug, forKey: .slug)
        try container.encodeIfPresent(number, forKey: .number)
        try container.encode(featureType, forKey: .featureType)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encode(status, forKey: .status)
    }
}

