//
// TerrainParkStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Operational status of a terrain park. */
public enum TerrainParkStatus: String, Sendable, Codable, CaseIterable {
    case `open` = "open"
    case closed = "closed"
    case unknown = "unknown"
}
