//
// TrailMapElement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A trail map element with full entity data from existing public models. */
public enum TrailMapElement: Sendable, Codable, Hashable {
    case typeTrailMapElementOneOf(TrailMapElementOneOf)
    case typeTrailMapElementOneOf1(TrailMapElementOneOf1)
    case typeTrailMapElementOneOf2(TrailMapElementOneOf2)
    case typeTrailMapElementOneOf3(TrailMapElementOneOf3)
    case typeTrailMapElementOneOf4(TrailMapElementOneOf4)
    case unknownDefaultOpenApi

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeTrailMapElementOneOf(let value):
            try container.encode(value)
        case .typeTrailMapElementOneOf1(let value):
            try container.encode(value)
        case .typeTrailMapElementOneOf2(let value):
            try container.encode(value)
        case .typeTrailMapElementOneOf3(let value):
            try container.encode(value)
        case .typeTrailMapElementOneOf4(let value):
            try container.encode(value)
        case .unknownDefaultOpenApi:
            try container.encodeNil()
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(TrailMapElementOneOf.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeTrailMapElementOneOf(value)
        } else if let value = try? container.decode(TrailMapElementOneOf1.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeTrailMapElementOneOf1(value)
        } else if let value = try? container.decode(TrailMapElementOneOf2.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeTrailMapElementOneOf2(value)
        } else if let value = try? container.decode(TrailMapElementOneOf3.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeTrailMapElementOneOf3(value)
        } else if let value = try? container.decode(TrailMapElementOneOf4.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeTrailMapElementOneOf4(value)
        } else {
            self = .unknownDefaultOpenApi
        }
    }
}

