//
// TrailMapStaticElementOneOf5.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TrailMapStaticElementOneOf5: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case parkingLotMarker = "parking_lot_marker"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var type: ModelType
    public var uuid: String
    public var x: Double
    public var y: Double
    public var icon: MarkerIcon?
    public var color: String?
    public var parkingLotUuid: String
    public var groupLabel: String?

    public init(type: ModelType, uuid: String, x: Double, y: Double, icon: MarkerIcon? = nil, color: String? = nil, parkingLotUuid: String, groupLabel: String? = nil) {
        self.type = type
        self.uuid = uuid
        self.x = x
        self.y = y
        self.icon = icon
        self.color = color
        self.parkingLotUuid = parkingLotUuid
        self.groupLabel = groupLabel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case uuid
        case x
        case y
        case icon
        case color
        case parkingLotUuid = "parking_lot_uuid"
        case groupLabel = "group_label"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(x, forKey: .x)
        try container.encode(y, forKey: .y)
        try container.encodeIfPresent(icon, forKey: .icon)
        try container.encodeIfPresent(color, forKey: .color)
        try container.encode(parkingLotUuid, forKey: .parkingLotUuid)
        try container.encodeIfPresent(groupLabel, forKey: .groupLabel)
    }
}


extension TrailMapStaticElementOneOf5: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if type == .unknownDefaultOpenApi { return true }
        if icon == .unknownDefaultOpenApi { return true }
        return false
    }
}
