//
// TrailMapStaticElementOneOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TrailMapStaticElementOneOf: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case lift = "lift"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var type: ModelType
    public var uuid: String
    public var points: [Double]
    public var tension: Double?
    public var liftUuid: String

    public init(type: ModelType, uuid: String, points: [Double], tension: Double? = nil, liftUuid: String) {
        self.type = type
        self.uuid = uuid
        self.points = points
        self.tension = tension
        self.liftUuid = liftUuid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case uuid
        case points
        case tension
        case liftUuid = "lift_uuid"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(points, forKey: .points)
        try container.encodeIfPresent(tension, forKey: .tension)
        try container.encode(liftUuid, forKey: .liftUuid)
    }
}


extension TrailMapStaticElementOneOf: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if type == .unknownDefaultOpenApi { return true }
        return false
    }
}
