//
// TrailMapStaticElement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A positioned trail-map element carrying only static geometry plus a UUID  reference to the entity it represents. Deliberately holds no entity object,  so nothing here changes unless the map&#39;s &#x60;version&#x60; bumps. Clients resolve the  referenced entity (and its live status) from the report by UUID. */
public enum TrailMapStaticElement: Sendable, Codable, Hashable {
    case typeTrailMapElementOneOf7(TrailMapElementOneOf7)
    case typeTrailMapStaticElementOneOf(TrailMapStaticElementOneOf)
    case typeTrailMapStaticElementOneOf1(TrailMapStaticElementOneOf1)
    case typeTrailMapStaticElementOneOf2(TrailMapStaticElementOneOf2)
    case typeTrailMapStaticElementOneOf3(TrailMapStaticElementOneOf3)
    case typeTrailMapStaticElementOneOf4(TrailMapStaticElementOneOf4)
    case typeTrailMapStaticElementOneOf5(TrailMapStaticElementOneOf5)
    case typeTrailMapStaticElementOneOf6(TrailMapStaticElementOneOf6)
    case unknownDefaultOpenApi

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeTrailMapElementOneOf7(let value):
            try container.encode(value)
        case .typeTrailMapStaticElementOneOf(let value):
            try container.encode(value)
        case .typeTrailMapStaticElementOneOf1(let value):
            try container.encode(value)
        case .typeTrailMapStaticElementOneOf2(let value):
            try container.encode(value)
        case .typeTrailMapStaticElementOneOf3(let value):
            try container.encode(value)
        case .typeTrailMapStaticElementOneOf4(let value):
            try container.encode(value)
        case .typeTrailMapStaticElementOneOf5(let value):
            try container.encode(value)
        case .typeTrailMapStaticElementOneOf6(let value):
            try container.encode(value)
        case .unknownDefaultOpenApi:
            try container.encodeNil()
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(TrailMapElementOneOf7.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeTrailMapElementOneOf7(value)
        } else if let value = try? container.decode(TrailMapStaticElementOneOf.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeTrailMapStaticElementOneOf(value)
        } else if let value = try? container.decode(TrailMapStaticElementOneOf1.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeTrailMapStaticElementOneOf1(value)
        } else if let value = try? container.decode(TrailMapStaticElementOneOf2.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeTrailMapStaticElementOneOf2(value)
        } else if let value = try? container.decode(TrailMapStaticElementOneOf3.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeTrailMapStaticElementOneOf3(value)
        } else if let value = try? container.decode(TrailMapStaticElementOneOf4.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeTrailMapStaticElementOneOf4(value)
        } else if let value = try? container.decode(TrailMapStaticElementOneOf5.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeTrailMapStaticElementOneOf5(value)
        } else if let value = try? container.decode(TrailMapStaticElementOneOf6.self), (value as? UnknownCaseCheckable)?.containsUnknownDefaultOpenApiCase != true {
            self = .typeTrailMapStaticElementOneOf6(value)
        } else {
            self = .unknownDefaultOpenApi
        }
    }
}

