//
// TrailMapStatic.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The static, geometry-only view of a trail map: artwork, positioned elements,  and geo control points, plus a UUID reference to each element&#39;s entity, but  **no** embedded entity data. Every field here is covered by the map&#39;s  &#x60;version&#x60;, so the serialized body is byte-stable for a fixed &#x60;version&#x60;. The  version is served in the URL, making each version an immutable resource —  clients (and CDNs) cache it long-lived and rehydrate live entity data  (status, wait times, grooming, …) from the report by UUID. */
public struct TrailMapStatic: Sendable, Codable, Hashable {

    public var uuid: String
    public var name: String
    public var slug: String
    public var season: SeasonType
    public var displayOrder: Int64
    /** Monotonically incremented whenever the map's static content (geometry,  artwork, element membership, or the metadata carried here) changes. This  body is byte-stable for a fixed `version`, and the `version` is part of  the request URL — so the resource is immutable per version. */
    public var version: Int64
    public var backgroundImageUrl: String
    public var elements: [TrailMapStaticElement]
    public var geoControlPoints: [GeoControlPoint]?

    public init(uuid: String, name: String, slug: String, season: SeasonType, displayOrder: Int64, version: Int64, backgroundImageUrl: String, elements: [TrailMapStaticElement], geoControlPoints: [GeoControlPoint]? = nil) {
        self.uuid = uuid
        self.name = name
        self.slug = slug
        self.season = season
        self.displayOrder = displayOrder
        self.version = version
        self.backgroundImageUrl = backgroundImageUrl
        self.elements = elements
        self.geoControlPoints = geoControlPoints
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case name
        case slug
        case season
        case displayOrder = "display_order"
        case version
        case backgroundImageUrl = "background_image_url"
        case elements
        case geoControlPoints = "geo_control_points"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(name, forKey: .name)
        try container.encode(slug, forKey: .slug)
        try container.encode(season, forKey: .season)
        try container.encode(displayOrder, forKey: .displayOrder)
        try container.encode(version, forKey: .version)
        try container.encode(backgroundImageUrl, forKey: .backgroundImageUrl)
        try container.encode(elements, forKey: .elements)
        try container.encodeIfPresent(geoControlPoints, forKey: .geoControlPoints)
    }
}


extension TrailMapStatic: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if season == .unknownDefaultOpenApi { return true }
        return false
    }
}
