//
// TrailMapElementOneOf2.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TrailMapElementOneOf2: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case terrainPark = "terrain_park"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var type: ModelType
    public var uuid: String
    public var points: [Double]
    public var tension: Double?
    public var labelOffset: LabelOffset?
    public var terrainPark: TerrainPark?

    public init(type: ModelType, uuid: String, points: [Double], tension: Double? = nil, labelOffset: LabelOffset? = nil, terrainPark: TerrainPark? = nil) {
        self.type = type
        self.uuid = uuid
        self.points = points
        self.tension = tension
        self.labelOffset = labelOffset
        self.terrainPark = terrainPark
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case uuid
        case points
        case tension
        case labelOffset = "label_offset"
        case terrainPark = "terrain_park"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(points, forKey: .points)
        try container.encodeIfPresent(tension, forKey: .tension)
        try container.encodeIfPresent(labelOffset, forKey: .labelOffset)
        try container.encodeIfPresent(terrainPark, forKey: .terrainPark)
    }
}


extension TrailMapElementOneOf2: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if type == .unknownDefaultOpenApi { return true }
        return false
    }
}
