//
// TrailMapElementOneOf4.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TrailMapElementOneOf4: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case pointMarker = "point_marker"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var type: ModelType

    public init(type: ModelType) {
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
    }
}


extension TrailMapElementOneOf4: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if type == .unknownDefaultOpenApi { return true }
        return false
    }
}
