//
// TrailMapStaticPath.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Path params for the versioned static endpoint: the map&#39;s UUID plus the  specific &#x60;version&#x60; the client is asking for. The version lives in the URL so  each version is an immutable resource (see &#x60;get_trail_map_static&#x60;). */
public struct TrailMapStaticPath: Sendable, Codable, Hashable {

    /** Trail map UUID */
    public var uuid: String
    /** The map version being requested (from `TrailMapSummary.version`) */
    public var version: Int64

    public init(uuid: String, version: Int64) {
        self.uuid = uuid
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(version, forKey: .version)
    }
}

