//
// TrailMapStaticElementOneOf1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TrailMapStaticElementOneOf1: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case run = "run"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var type: ModelType
    public var uuid: String
    public var points: [Double]
    public var tension: Double?
    public var geometry: GeometryMode?
    public var labelOffset: LabelOffset?
    public var runUuid: String

    public init(type: ModelType, uuid: String, points: [Double], tension: Double? = nil, geometry: GeometryMode? = nil, labelOffset: LabelOffset? = nil, runUuid: String) {
        self.type = type
        self.uuid = uuid
        self.points = points
        self.tension = tension
        self.geometry = geometry
        self.labelOffset = labelOffset
        self.runUuid = runUuid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case uuid
        case points
        case tension
        case geometry
        case labelOffset = "label_offset"
        case runUuid = "run_uuid"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(points, forKey: .points)
        try container.encodeIfPresent(tension, forKey: .tension)
        try container.encodeIfPresent(geometry, forKey: .geometry)
        try container.encodeIfPresent(labelOffset, forKey: .labelOffset)
        try container.encode(runUuid, forKey: .runUuid)
    }
}


extension TrailMapStaticElementOneOf1: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if type == .unknownDefaultOpenApi { return true }
        if geometry == .unknownDefaultOpenApi { return true }
        return false
    }
}
