//
// TrailMapElementOneOf3.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TrailMapElementOneOf3: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case summerTrail = "summer_trail"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var type: ModelType
    public var uuid: String
    public var points: [Double]
    public var tension: Double?
    public var summerTrail: SummerTrail?

    public init(type: ModelType, uuid: String, points: [Double], tension: Double? = nil, summerTrail: SummerTrail? = nil) {
        self.type = type
        self.uuid = uuid
        self.points = points
        self.tension = tension
        self.summerTrail = summerTrail
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case uuid
        case points
        case tension
        case summerTrail = "summer_trail"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(points, forKey: .points)
        try container.encodeIfPresent(tension, forKey: .tension)
        try container.encodeIfPresent(summerTrail, forKey: .summerTrail)
    }
}


extension TrailMapElementOneOf3: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        if type == .unknownDefaultOpenApi { return true }
        return false
    }
}
