//
// UnitPreference.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Unit preference (cm/in, km/miles, etc.) */
public enum UnitPreference: String, Sendable, Codable, CaseIterable {
    case metric = "metric"
    case imperial = "imperial"
}
