//
// WeatherConditionCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Weather condition code   Variants mirror Apple&#39;s &#x60;WeatherCondition&#x60; enum exactly so they match the  &#x60;conditionCode&#x60; strings returned by the WeatherKit REST API verbatim.  See https://developer.apple.com/documentation/weatherkit/weathercondition */
public enum WeatherConditionCode: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case clear = "Clear"
    case cloudy = "Cloudy"
    case foggy = "Foggy"
    case haze = "Haze"
    case mostlyClear = "MostlyClear"
    case mostlyCloudy = "MostlyCloudy"
    case partlyCloudy = "PartlyCloudy"
    case smoky = "Smoky"
    case blowingDust = "BlowingDust"
    case breezy = "Breezy"
    case windy = "Windy"
    case drizzle = "Drizzle"
    case heavyRain = "HeavyRain"
    case isolatedThunderstorms = "IsolatedThunderstorms"
    case rain = "Rain"
    case sunShowers = "SunShowers"
    case scatteredThunderstorms = "ScatteredThunderstorms"
    case strongStorms = "StrongStorms"
    case thunderstorms = "Thunderstorms"
    case frigid = "Frigid"
    case hail = "Hail"
    case hot = "Hot"
    case flurries = "Flurries"
    case sleet = "Sleet"
    case snow = "Snow"
    case sunFlurries = "SunFlurries"
    case wintryMix = "WintryMix"
    case blizzard = "Blizzard"
    case blowingSnow = "BlowingSnow"
    case freezingDrizzle = "FreezingDrizzle"
    case freezingRain = "FreezingRain"
    case heavySnow = "HeavySnow"
    case hurricane = "Hurricane"
    case tropicalStorm = "TropicalStorm"
    case unknown = "Unknown"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}

extension WeatherConditionCode: UnknownCaseCheckable {
    public var containsUnknownDefaultOpenApiCase: Bool {
        self == .unknownDefaultOpenApi
    }
}
