//
// Weather.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Current and forecasted weather conditions for the resort&#39;s location.  Only included/available if the weather feature is enabled and GPS coordinates are configured. */
public struct Weather: Sendable, Codable, Hashable {

    /** Current weather conditions */
    public var current: CurrentWeather
    /** Hourly forecast for next 24 hours (including current hour) */
    public var hourlyForecast: [HourlyForecast]
    /** Daily forecast for next 7 days (including today) */
    public var dailyForecast: [DailyForecast]
    /** Data source attribution */
    public var attribution: String
    /** When this data was last updated */
    public var updatedAt: Date

    public init(current: CurrentWeather, hourlyForecast: [HourlyForecast], dailyForecast: [DailyForecast], attribution: String, updatedAt: Date) {
        self.current = current
        self.hourlyForecast = hourlyForecast
        self.dailyForecast = dailyForecast
        self.attribution = attribution
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case current
        case hourlyForecast = "hourly_forecast"
        case dailyForecast = "daily_forecast"
        case attribution
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(current, forKey: .current)
        try container.encode(hourlyForecast, forKey: .hourlyForecast)
        try container.encode(dailyForecast, forKey: .dailyForecast)
        try container.encode(attribution, forKey: .attribution)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

