//
// WeatherConditionCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Weather condition code */
public enum WeatherConditionCode: String, Sendable, Codable, CaseIterable {
    case clear = "Clear"
    case mostlyClear = "MostlyClear"
    case partlyCloudy = "PartlyCloudy"
    case mostlyCloudy = "MostlyCloudy"
    case cloudy = "Cloudy"
    case dust = "Dust"
    case fog = "Fog"
    case haze = "Haze"
    case smoke = "Smoke"
    case breezy = "Breezy"
    case windy = "Windy"
    case drizzle = "Drizzle"
    case rain = "Rain"
    case showers = "Showers"
    case scatteredShowers = "ScatteredShowers"
    case heavyRain = "HeavyRain"
    case flurries = "Flurries"
    case snow = "Snow"
    case snowShowers = "SnowShowers"
    case scatteredSnowShowers = "ScatteredSnowShowers"
    case heavySnow = "HeavySnow"
    case blizzard = "Blizzard"
    case blowingSnow = "BlowingSnow"
    case mixedRainAndSleet = "MixedRainAndSleet"
    case mixedRainAndSnow = "MixedRainAndSnow"
    case mixedRainfall = "MixedRainfall"
    case mixedSnowAndSleet = "MixedSnowAndSleet"
    case sleet = "Sleet"
    case freezingDrizzle = "FreezingDrizzle"
    case freezingRain = "FreezingRain"
    case frigid = "Frigid"
    case hail = "Hail"
    case scatteredThunderstorms = "ScatteredThunderstorms"
    case isolatedThunderstorms = "IsolatedThunderstorms"
    case thunderstorm = "Thunderstorm"
    case severeThunderstorm = "SevereThunderstorm"
    case hurricane = "Hurricane"
    case tornado = "Tornado"
    case tropicalStorm = "TropicalStorm"
    case hot = "Hot"
    case unknown = "Unknown"
}
