//
// Webcam.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A public webcam entry. Consumers pick &#x60;latest&#x60; (always the newest frame) or  &#x60;latest-daylight&#x60; (the last daylight frame, never a black night shot)  depending on whether they want the freshest or a guaranteed-lit image. */
public struct Webcam: Sendable, Codable, Hashable {

    public var uuid: String
    public var name: String
    public var areaUuid: String?
    public var areaName: String?
    public var areaDisplayOrder: Int?
    /** URL of the newest frame (refreshes within ~60s via the edge cache). */
    public var latestImageUrl: String
    /** URL of the last daylight frame. */
    public var latestDaylightImageUrl: String
    public var latestThumbUrl: String
    public var latestDaylightThumbUrl: String
    /** ThumbHash of the `latest` frame (standard base64) — a compact blur  placeholder to render while the image loads. Empty string until the first  frame (or on cameras predating the feature). */
    public var latestThumbhash: String
    /** ThumbHash of the `latest-daylight` frame (standard base64). Empty string  until the first daylight frame. */
    public var latestDaylightThumbhash: String
    /** Whether this camera archives frames — i.e. whether its history endpoint  returns anything. When `false`, don't call the history API for it. */
    public var hasHistory: Bool
    /** Camera elevation in both units; omitted when unset. */
    public var elevationFt: Int?
    public var elevationM: Int?
    /** Time of the most recently published frame; omitted until the first frame. */
    public var lastFrameAt: String?

    public init(uuid: String, name: String, areaUuid: String? = nil, areaName: String? = nil, areaDisplayOrder: Int? = nil, latestImageUrl: String, latestDaylightImageUrl: String, latestThumbUrl: String, latestDaylightThumbUrl: String, latestThumbhash: String, latestDaylightThumbhash: String, hasHistory: Bool, elevationFt: Int? = nil, elevationM: Int? = nil, lastFrameAt: String? = nil) {
        self.uuid = uuid
        self.name = name
        self.areaUuid = areaUuid
        self.areaName = areaName
        self.areaDisplayOrder = areaDisplayOrder
        self.latestImageUrl = latestImageUrl
        self.latestDaylightImageUrl = latestDaylightImageUrl
        self.latestThumbUrl = latestThumbUrl
        self.latestDaylightThumbUrl = latestDaylightThumbUrl
        self.latestThumbhash = latestThumbhash
        self.latestDaylightThumbhash = latestDaylightThumbhash
        self.hasHistory = hasHistory
        self.elevationFt = elevationFt
        self.elevationM = elevationM
        self.lastFrameAt = lastFrameAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case name
        case areaUuid = "area_uuid"
        case areaName = "area_name"
        case areaDisplayOrder = "area_display_order"
        case latestImageUrl = "latest_image_url"
        case latestDaylightImageUrl = "latest_daylight_image_url"
        case latestThumbUrl = "latest_thumb_url"
        case latestDaylightThumbUrl = "latest_daylight_thumb_url"
        case latestThumbhash = "latest_thumbhash"
        case latestDaylightThumbhash = "latest_daylight_thumbhash"
        case hasHistory = "has_history"
        case elevationFt = "elevation_ft"
        case elevationM = "elevation_m"
        case lastFrameAt = "last_frame_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(areaUuid, forKey: .areaUuid)
        try container.encodeIfPresent(areaName, forKey: .areaName)
        try container.encodeIfPresent(areaDisplayOrder, forKey: .areaDisplayOrder)
        try container.encode(latestImageUrl, forKey: .latestImageUrl)
        try container.encode(latestDaylightImageUrl, forKey: .latestDaylightImageUrl)
        try container.encode(latestThumbUrl, forKey: .latestThumbUrl)
        try container.encode(latestDaylightThumbUrl, forKey: .latestDaylightThumbUrl)
        try container.encode(latestThumbhash, forKey: .latestThumbhash)
        try container.encode(latestDaylightThumbhash, forKey: .latestDaylightThumbhash)
        try container.encode(hasHistory, forKey: .hasHistory)
        try container.encodeIfPresent(elevationFt, forKey: .elevationFt)
        try container.encodeIfPresent(elevationM, forKey: .elevationM)
        try container.encodeIfPresent(lastFrameAt, forKey: .lastFrameAt)
    }
}

