//
// WebcamHistoryFrame.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A single archived historical frame. */
public struct WebcamHistoryFrame: Sendable, Codable, Hashable {

    public var capturedAt: String
    public var imageUrl: String
    public var thumbUrl: String

    public init(capturedAt: String, imageUrl: String, thumbUrl: String) {
        self.capturedAt = capturedAt
        self.imageUrl = imageUrl
        self.thumbUrl = thumbUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case capturedAt = "captured_at"
        case imageUrl = "image_url"
        case thumbUrl = "thumb_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(capturedAt, forKey: .capturedAt)
        try container.encode(imageUrl, forKey: .imageUrl)
        try container.encode(thumbUrl, forKey: .thumbUrl)
    }
}

