//
// WebcamHistoryResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The historical frame listing for one camera over a time range. */
public struct WebcamHistoryResponse: Sendable, Codable, Hashable {

    public var webcamUuid: String
    /** Newest first. */
    public var frames: [WebcamHistoryFrame]

    public init(webcamUuid: String, frames: [WebcamHistoryFrame]) {
        self.webcamUuid = webcamUuid
        self.frames = frames
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case webcamUuid = "webcam_uuid"
        case frames
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(webcamUuid, forKey: .webcamUuid)
        try container.encode(frames, forKey: .frames)
    }
}

