//
// Webcam.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A public webcam entry. Consumers pick &#x60;latest&#x60; (always the newest frame) or  &#x60;latest-daylight&#x60; (the last daylight frame, never a black night shot)  depending on whether they want the freshest or a guaranteed-lit image. */
public struct Webcam: Sendable, Codable, Hashable {

    public var uuid: String
    public var name: String
    public var areaUuid: String?
    public var areaName: String?
    public var areaDisplayOrder: Int?
    /** URL of the newest frame (refreshes within ~60s via the edge cache). */
    public var latestImageUrl: String
    /** URL of the last daylight frame. */
    public var latestDaylightImageUrl: String
    public var latestThumbUrl: String
    public var latestDaylightThumbUrl: String
    /** Time of the most recently published frame; omitted until the first frame. */
    public var lastFrameAt: String?

    public init(uuid: String, name: String, areaUuid: String? = nil, areaName: String? = nil, areaDisplayOrder: Int? = nil, latestImageUrl: String, latestDaylightImageUrl: String, latestThumbUrl: String, latestDaylightThumbUrl: String, lastFrameAt: String? = nil) {
        self.uuid = uuid
        self.name = name
        self.areaUuid = areaUuid
        self.areaName = areaName
        self.areaDisplayOrder = areaDisplayOrder
        self.latestImageUrl = latestImageUrl
        self.latestDaylightImageUrl = latestDaylightImageUrl
        self.latestThumbUrl = latestThumbUrl
        self.latestDaylightThumbUrl = latestDaylightThumbUrl
        self.lastFrameAt = lastFrameAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case name
        case areaUuid = "area_uuid"
        case areaName = "area_name"
        case areaDisplayOrder = "area_display_order"
        case latestImageUrl = "latest_image_url"
        case latestDaylightImageUrl = "latest_daylight_image_url"
        case latestThumbUrl = "latest_thumb_url"
        case latestDaylightThumbUrl = "latest_daylight_thumb_url"
        case lastFrameAt = "last_frame_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(areaUuid, forKey: .areaUuid)
        try container.encodeIfPresent(areaName, forKey: .areaName)
        try container.encodeIfPresent(areaDisplayOrder, forKey: .areaDisplayOrder)
        try container.encode(latestImageUrl, forKey: .latestImageUrl)
        try container.encode(latestDaylightImageUrl, forKey: .latestDaylightImageUrl)
        try container.encode(latestThumbUrl, forKey: .latestThumbUrl)
        try container.encode(latestDaylightThumbUrl, forKey: .latestDaylightThumbUrl)
        try container.encodeIfPresent(lastFrameAt, forKey: .lastFrameAt)
    }
}

