//
// MtnManagerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class MtnManagerAPI {

    /**
     Get full report
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: FullReport
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getFullReport(apiConfiguration: MtnManagerSDKAPIConfiguration = MtnManagerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> FullReport {
        return try await getFullReportWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get full report
     - GET /api/v1/report
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<FullReport> 
     */
    open class func getFullReportWithRequestBuilder(apiConfiguration: MtnManagerSDKAPIConfiguration = MtnManagerSDKAPIConfiguration.shared) -> RequestBuilder<FullReport> {
        let localVariablePath = "/api/v1/report"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<FullReport>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get operating hours
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: OperatingHours
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getHours(apiConfiguration: MtnManagerSDKAPIConfiguration = MtnManagerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> OperatingHours {
        return try await getHoursWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get operating hours
     - GET /api/v1/report/hours
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OperatingHours> 
     */
    open class func getHoursWithRequestBuilder(apiConfiguration: MtnManagerSDKAPIConfiguration = MtnManagerSDKAPIConfiguration.shared) -> RequestBuilder<OperatingHours> {
        let localVariablePath = "/api/v1/report/hours"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OperatingHours>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get lifts
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [Lift]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getLifts(apiConfiguration: MtnManagerSDKAPIConfiguration = MtnManagerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [Lift] {
        return try await getLiftsWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get lifts
     - GET /api/v1/report/lifts
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[Lift]> 
     */
    open class func getLiftsWithRequestBuilder(apiConfiguration: MtnManagerSDKAPIConfiguration = MtnManagerSDKAPIConfiguration.shared) -> RequestBuilder<[Lift]> {
        let localVariablePath = "/api/v1/report/lifts"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Lift]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get overview
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Overview
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getOverview(apiConfiguration: MtnManagerSDKAPIConfiguration = MtnManagerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> Overview {
        return try await getOverviewWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get overview
     - GET /api/v1/report/overview
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Overview> 
     */
    open class func getOverviewWithRequestBuilder(apiConfiguration: MtnManagerSDKAPIConfiguration = MtnManagerSDKAPIConfiguration.shared) -> RequestBuilder<Overview> {
        let localVariablePath = "/api/v1/report/overview"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Overview>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get parking lots
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [ParkingLot]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getParkingLots(apiConfiguration: MtnManagerSDKAPIConfiguration = MtnManagerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [ParkingLot] {
        return try await getParkingLotsWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get parking lots
     - GET /api/v1/report/parking-lots
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[ParkingLot]> 
     */
    open class func getParkingLotsWithRequestBuilder(apiConfiguration: MtnManagerSDKAPIConfiguration = MtnManagerSDKAPIConfiguration.shared) -> RequestBuilder<[ParkingLot]> {
        let localVariablePath = "/api/v1/report/parking-lots"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ParkingLot]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get runs
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [Run]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRuns(apiConfiguration: MtnManagerSDKAPIConfiguration = MtnManagerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [Run] {
        return try await getRunsWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get runs
     - GET /api/v1/report/runs
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[Run]> 
     */
    open class func getRunsWithRequestBuilder(apiConfiguration: MtnManagerSDKAPIConfiguration = MtnManagerSDKAPIConfiguration.shared) -> RequestBuilder<[Run]> {
        let localVariablePath = "/api/v1/report/runs"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Run]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get snow conditions
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [SnowReport]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getSnow(apiConfiguration: MtnManagerSDKAPIConfiguration = MtnManagerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [SnowReport] {
        return try await getSnowWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get snow conditions
     - GET /api/v1/report/snow
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[SnowReport]> 
     */
    open class func getSnowWithRequestBuilder(apiConfiguration: MtnManagerSDKAPIConfiguration = MtnManagerSDKAPIConfiguration.shared) -> RequestBuilder<[SnowReport]> {
        let localVariablePath = "/api/v1/report/snow"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[SnowReport]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get summer trails
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [SummerTrail]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getSummerTrails(apiConfiguration: MtnManagerSDKAPIConfiguration = MtnManagerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [SummerTrail] {
        return try await getSummerTrailsWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get summer trails
     - GET /api/v1/report/summer-trails
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[SummerTrail]> 
     */
    open class func getSummerTrailsWithRequestBuilder(apiConfiguration: MtnManagerSDKAPIConfiguration = MtnManagerSDKAPIConfiguration.shared) -> RequestBuilder<[SummerTrail]> {
        let localVariablePath = "/api/v1/report/summer-trails"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[SummerTrail]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get terrain parks
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [TerrainPark]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getTerrainParks(apiConfiguration: MtnManagerSDKAPIConfiguration = MtnManagerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [TerrainPark] {
        return try await getTerrainParksWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get terrain parks
     - GET /api/v1/report/terrain-parks
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[TerrainPark]> 
     */
    open class func getTerrainParksWithRequestBuilder(apiConfiguration: MtnManagerSDKAPIConfiguration = MtnManagerSDKAPIConfiguration.shared) -> RequestBuilder<[TerrainPark]> {
        let localVariablePath = "/api/v1/report/terrain-parks"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[TerrainPark]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get weather
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Weather
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getWeather(apiConfiguration: MtnManagerSDKAPIConfiguration = MtnManagerSDKAPIConfiguration.shared) async throws(ErrorResponse) -> Weather {
        return try await getWeatherWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get weather
     - GET /api/v1/report/weather
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Weather> 
     */
    open class func getWeatherWithRequestBuilder(apiConfiguration: MtnManagerSDKAPIConfiguration = MtnManagerSDKAPIConfiguration.shared) -> RequestBuilder<Weather> {
        let localVariablePath = "/api/v1/report/weather"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Weather>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
